### ISSUE TITLE
3.2.1.develop support

### ISSUE THREAD

**Issue by Hagall69** [dkuk/global_roles#3]
Help plz!!!

rake aborted!
ArgumentError: Unknown key: :include. Valid keys are: :class_name, :anonymous_class, :foreign_key, :validate, :autosave, :table_name, :before_add, :after_add, :before_remove, :after_remove, :extend, :primary_key, :dependent, :as, :through, :source, :source_type, :inverse_of, :counter_cache, :join_table, :foreign_type
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:75:in `block in assert_valid_keys'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:73:in`each_key'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/core_ext/hash/keys.rb:73:in `assert_valid_keys'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:82:in`validate_options'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:62:in `initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/collection_association.rb:18:in`initialize'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:47:in `new'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:47:in`create_builder'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations/builder/association.rb:35:in `build'
/var/lib/gems/2.1.0/gems/activerecord-4.2.5.2/lib/active_record/associations.rb:1259:in`has_many'
/usr/redmine/plugins/global_roles/lib/global_roles/role_patch.rb:12:in `block in included'
/usr/redmine/plugins/global_roles/lib/global_roles/role_patch.rb:7:in`class_eval'
/usr/redmine/plugins/global_roles/lib/global_roles/role_patch.rb:7:in `included'
/usr/redmine/plugins/global_roles/init.rb:19:in`include'
/usr/redmine/plugins/global_roles/init.rb:19:in `block in <top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in`instance_exec'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:446:in `block in make_lambda'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in`call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:192:in `block in simple'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in`call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `block in call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in`each'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:504:in `call'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:92:in`**run_callbacks**'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:778:in `_run_prepare_callbacks'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/callbacks.rb:81:in`run_callbacks'
/var/lib/gems/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
/var/lib/gems/2.1.0/gems/actionpack-4.2.5.2/lib/action_dispatch/middleware/reloader.rb:55:in`prepare!'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in`instance_exec'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:55:in`block in run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/application.rb:352:in`initialize!'
/usr/redmine/config/environment.rb:14:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in`require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `block in require'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:274:in `require'
/usr/redmine/plugins/a_common_libs/lib/tasks/saas.rake:1:in`<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in`block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in`load'
/usr/redmine/lib/tasks/redmine.rake:186:in `block in <top (required)>'
/usr/redmine/lib/tasks/redmine.rake:186:in`each'
/usr/redmine/lib/tasks/redmine.rake:186:in `<top (required)>'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in`load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `block in load'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:240:in`load_dependency'
/var/lib/gems/2.1.0/gems/activesupport-4.2.5.2/lib/active_support/dependencies.rb:268:in `load'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in`block in run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in `each'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/engine.rb:658:in`run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/application.rb:452:in `run_tasks_blocks'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/engine.rb:453:in`load_tasks'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in `public_send'
/var/lib/gems/2.1.0/gems/railties-4.2.5.2/lib/rails/railtie.rb:194:in`method_missing'
/usr/redmine/Rakefile:7:in `<top (required)>'

**Comment by SkiF91** [comment]
Hello. All our projects was moved to bitbucket.
Last our global roles you can find here: https://bitbucket.org/dkuk/global_roles
In master branch - version for RM 2.5 - 3.1.1
In development - RM 2.5 - 3.1.1 and beta for RM 3.2
